### ISSUE TITLE
Error in read function from ase.io library

### ISSUE THREAD

**Issue by jaindipak21** [kaist-amsg/imatgen#1]
I am getting the below error when I try to run the following lines of code 
![image](https://user-images.githubusercontent.com/59616851/71911865-825bcb80-319a-11ea-9dd8-7eaa07960d2e.png)

import argparse
from ase.io import read, write
from ase.io import iread
import numpy as np
from ase import Atom, Atoms
parser = argparse.ArgumentParser(description='mapping POSCAR or cif structure into a box image')
parser.add_argument('--input_file', type=str,nargs='+',
                        help='a file path with the poscar or cif structure')
parser.add_argument('--filetype', type=str,default='cif',
                        help='filetype : cif,vasp')
parser.add_argument('--nbins', type=int,default=32,
            help='number of bins in one dimension')
parser.add_argument('--nproc', type=int,default=1,
            help='number of process')
args = parser.parse_args()
inputfile = args.input_file
filetype = args.filetype
print(inputfile)
print(filetype)
atoms = read(inputfile,format = args.filetype, parallel = False)

My command line input is the following 
python prog.py --input_file D:\deepak\coding practice\iMatGen-VO_dataset_generated_strctures\VO_dataset\geometries\mp-170_copy1_opt.vasp --file_type vasp --nbins 20 --nproc 1

**Comment by goodwilling** [comment]
It seems that iMatGen can not be run in Python 3 ...

**Comment by jhwann** [comment]
Sorry for late reply, currently iMatGen is running on Python2
