### ISSUE TITLE
About MP subset data

### ISSUE THREAD

**Issue by nissy-dev** [kaist-amsg/imatgen#2]
@jhwann 
Hi, I'm a master student in Japan.
Thank you for sharing codes and data about the iMatGen.
I'm interested in your research and trying to reproduce the result using Pytorch.

When I'm reading the Supplemental Information, I wonder how to get the MP subset data. Especially, I couldn't understand the two constraints in the following sentence.

> we trained iMatGen using the MP subset consisting of
28,242 crystal structures taken from the MP database (up to 5 atom types in the unit cell)
satisfying two constraints as mentioned in the main text to obtain pre-trained model parameters
for IC and MG (without formation energy classification task)

What is the two constraints...? 
I think the main paper didn't mention about them. I want to know the details about MP subset.

**Comment by jhwann** [comment]
We mentioned two constraints at the 'Construction of VO Dataset' section.
"the maximum number of atoms in unit cell Nsites <= 20 and the maximum length of unit cell <= 10A "

**Comment by nissy-dev** [comment]
Thank you for a quick response !  I  really appreciate your help 👍
